#!/bin/bash
HRA=0
DA=0
gross_salary=0

if [ "$1" -lt 1500 ]
then
	HRA=$(($1 * 10 / 100))
	DA=$(($1 * 90 / 100 ))
	gross_salary=$(($HRA + $DA + $1))
	printf "%s\n" "Gross salary: $gross_salary" 
else
	DA=$(($1 * 98 / 100 ))
        gross_salary=$((500 + $DA + $1))
        printf "%s\n" "Gross salary: $gross_salary" 
fi
exit
