#!/bin/bash

if [ "$#" -lt 3 ]
then
	echo "Invalid number of arguments" >&2
	exit 1

elif [ "$2" -ge "$3" ]
then
	echo "Argument 2 is greater argument 3" >&2
	exit 2

else
	head -n $(( $3-1 )) "$1" | tail -n "$(( $3 - $2 - 1 ))"
	exit 0

fi

